### ISSUE TITLE
some new keybindings annoyances

### ISSUE THREAD

**Issue by apm256** [astroidmail/astroid#205]
I'm not very comfortable with the new keybindings (e.g. 'C-w' in place of 'x', etc). And I'm trying to go back to something more in my taste. In the process, I've encountered the following issues:
1. using 'shift+space' to page up in a thread:
 `thread_view.page_down=Space` works, but I could not figure how to configure `thread_view.page_up=Shift+Space`
2. `thread_view.search.search=/` doesn't work anymore in a VI-like way (I could not find how to separate "find new" and "find next")
3. I was used, in thread view, to hit Tab (ot Shift-Tab) then C-Enter to open links in a browser through a keyboard-only way. This is not possible anymore due to `thread_view.next_unread=Key (GDK_KEY_Tab)`. As a workaround, I've assigned to `thread_view.next_unread` some random key, but is there a way to unbind a key from the conf?

**Comment by gauteh** [comment]
apm256 writes on august 29, 2016 13:52:
> I'm not very comfortable with the new keybindings (e.g. 'C-w' in place of 'x', etc). And I'm trying to go back to something more in my taste. In the process, I've encountered the following issues:
> 1. using 'shift+space' to page up in a thread:
>  `thread_view.page_down=Space` works, but I could not figure how to configure `thread_view.page_up=Shift+Space`

It would be something like S-Space, but unfortunately adding shift as a
modfier is a bit complicated: #170.

> 2. `thread_view.search.search=/` doesn't work anymore in a VI-like way (I could not find how to separate "find new" and "find next")

Yes.. I realized I had shadowed 'n'/'N' which usually did some other
stuff. So I changed it to either open an search or go to the next.
Cancel with Esc. Maybe this isn't so great..

> 3. I was used, in thread view, to hit Tab (ot Shift-Tab) then C-Enter to open links in a browser through a keyboard-only way. This is not possible anymore due to `thread_view.next_unread=Key (GDK_KEY_Tab)`. As a workaround, I've assigned to `thread_view.next_unread` some random key, but is there a way to unbind a key from the conf?
> 

I just pushed a change so you can specify:

thread_view.next_unread=

to just drop that target.

**Comment by apm256** [comment]
Thank you for these explanations!

> Yes.. I realized I had shadowed 'n'/'N' which usually did some other
> stuff. So I changed it to either open an search or go to the next.
> Cancel with Esc. Maybe this isn't so great..

In my point of view, as `thread_view.search.next` and
`thread_view.search.previous` still exist, a new
`thread_view.search.search_or_next` side by side with the old
`thread_view.search.search` would be the best option.

> I just pushed a change so you can specify:
> thread_view.next_unread=
> to just drop that target.

Tested, and it works: thanks for this.

**Comment by gauteh** [comment]
apm256 writes on august 29, 2016 16:13:
> Thank you for these explanations!
> 
>> Yes.. I realized I had shadowed 'n'/'N' which usually did some other
>> stuff. So I changed it to either open an search or go to the next.
>> Cancel with Esc. Maybe this isn't so great..
> 
> In my point of view, as `thread_view.search.next` and
> `thread_view.search.previous` still exist, a new
> `thread_view.search.search_or_next` side by side with the old
> `thread_view.search.search` would be the best option.

I've added more specific search operations as unbound keys, you can
now configure the old behavior if you want.

**Comment by gauteh** [comment]
Closing, since the rest is covered in #170.

**Comment by apm256** [comment]
> I've added more specific search operations as unbound keys, you can
now configure the old behavior if you want.

great!
