### ISSUE TITLE
gpg: too many open files / high cpu usage

### ISSUE THREAD

**Issue by emdete** [astroidmail/astroid#241]
i encounter the error "too many open files" quite often since i use gpg with every email.

maybe something's broken in the usage of gpg?

**Comment by gauteh** [comment]
Have you confirmed this to be only with GPG? Does this happen when you have astroid running for a very long time? Do you have any logs?

Does astroid leave any gpg instances open?

**Comment by gauteh** [comment]
M. Dietrich writes on desember 7, 2016 17:20:
> i encounter the error "too many open files" quite often since i use gpg with every email.

Test latest master, I had forgotten to unref the gpg context.

**Comment by gauteh** [comment]
Closing, please re-open if issue persists.

**Comment by hugoroy** [comment]
Astroid seems to leave a lot of gpg instances open, yes (and gpg hangs at 100%CPU since yesterday)

**Comment by gauteh** [comment]
Hugo Roy writes on desember 9, 2016 16:10:
> Astroid seems to leave a lot of gpg instances open, yes (and gpg hangs at 100%CPU since yesterday)

Still the case after 4e523d6f375d4050e5a53143885f7712f5bacf91?

**Comment by hugoroy** [comment]
↪ Gaute Hope, décembre 9, 2016 4:21 :
> Hugo Roy writes on desember 9, 2016 16:10:
>> Astroid seems to leave a lot of gpg instances open, yes (and gpg hangs at 100%CPU since yesterday)
> 
> Still the case after 4e523d6f375d4050e5a53143885f7712f5bacf91?
> 

Yes, just recompiled master with the AUR.

Actually now, as soon as astroid starts, it spawns a gpg2 and seahorse
(which apparently are hanging on something at 100%CPU).

**Comment by gauteh** [comment]
I don't see how that can happen without opening an e-mail thread? Is it something that goes though the polling script and notmuch indexing of encrypted e-mails?

**Comment by hugoroy** [comment]
I downgraded gnupg. Not sure what the problem is exactly, but it doesn't seem to be astroid :)

**Comment by gauteh** [comment]
What is the problematic gnupg version? We should check if other notmuch users have the same problem, otherwise maybe report a gmime / gnupg bug.

**Comment by hugoroy** [comment]
2.1.16. 

I unfortunately won't have the time to dig further :)

**Comment by gauteh** [comment]
@emdete can you confirm whether your bug is either fixed by 4e523d6 or related to the gnupg version?

**Comment by gauteh** [comment]
There is should have been a recent libgcrypt release, the issue might be fixed after that.

**Comment by emdete** [comment]
yes, it happens when astroid runs for days. i will check new HEAD and let you know.

**Comment by gauteh** [comment]
Closing unless new info comes up.

**Comment by emdete** [comment]
the feature still exists :(

it now mainly gets stuck when starting the embedded editor (happened 3 times for me now).

**Comment by gauteh** [comment]
what version of gnupg do you have?

**Comment by gauteh** [comment]
@mxmehl, @emdete: what version of gnupg is causing issues?

**Comment by gauteh** [comment]
Please try #286, as well as running `scons test`. Was finally able to make a test case that caught this error.

**Comment by mxmehl** [comment]
Tests with `crypto-too-many-files` ran without errors. But from now on I'll log all output to a file (using -l) so we can track down the bug.

**Comment by gauteh** [comment]
M. Dietrich writes on januar 31, 2017 20:09:
> the feature still exists :(
> 
> it now mainly gets stuck when starting the embedded editor (happened 3 times for me now).
> 

mainly or only?

**Comment by gauteh** [comment]
For both; what is the output of: `ulimit -n` and `ulimit -Hn`.

**Comment by mxmehl** [comment]
> For both; what is the output of: ulimit -n and ulimit -Hn.

1024 and 4096

**Comment by mxmehl** [comment]
With the crypto branch, I experience strange, reproducable crashes:

1. Open a thread, containing encrypted (or only encrypted?) mails
2. Close the thread by pressing "x" in my case

Log from opening and closing the thread:

```
[13:23:16.137799] [0x00007febd50c7a00] [debug] ti: open thread: 000000000000915a (true)
[13:23:16.139516] [0x00007febd50c7a00] [debug] theme: loading..
[13:23:16.139643] [0x00007febd50c7a00] [info] re: using installed resource: /usr/share/astroid/ui/thread-view.html
[13:23:16.139844] [0x00007febd50c7a00] [debug] tv: testing version: 4
[13:23:16.139950] [0x00007febd50c7a00] [info] re: using user configured resource: /home/max/ui/thread-view.scss
[13:23:16.140081] [0x00007febd50c7a00] [debug] tv: testing version: 3
[13:23:16.140161] [0x00007febd50c7a00] [error] tv: scss file version does not match!
[13:23:16.140696] [0x00007febd50c7a00] [info] theme: processing: /home/max/.config/astroid/ui/thread-view.scss
[13:23:16.247198] [0x00007febd50c7a00] [info] tv: load thread: 000000000000915a
[13:23:16.247324] [0x00007febd50c7a00] [info] db: open db read-only, waiting for lock..
[13:23:16.247367] [0x00007febd50c7a00] [debug] db: read-only got lock.
[13:23:16.247701] [0x00007febd50c7a00] [debug] db: open time: 0.377 ms.
[13:23:16.248794] [0x00007febd50c7a00] [info] msg: loading mid: 4d4ea9bc-d967-3e3b-d968-74c533af61e3@golem.de
[13:23:16.248937] [0x00007febd50c7a00] [info] msg: filename: /home/max/Mails/FSFE/Lists.Outreach-de/cur/1487537504_0.30872.bistromath,U=1,FMD5=61a48fd53dacd4afb2d4d3dde1f46206:2,S
[13:23:16.249526] [0x00007febd50c7a00] [debug] chunk (0): content-type: multipart/encrypted
[13:23:16.249600] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.249717] [0x00007febd50c7a00] [debug] crypto: gpg: gpg2
[13:23:16.270984] [0x00007febd50c7a00] [warning] chunk: is encrypted.
[13:23:16.271079] [0x00007febd50c7a00] [debug] crypto: decrypting and verifiying..
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
[13:23:16.477713] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [20E7C60CC8******]
[13:23:16.477781] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [94E4C04********]
[13:23:16.477799] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [8B2FE9E6B*******]
[13:23:16.477815] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [5B19FA89F*******]
[13:23:16.477831] [0x00007febd50c7a00] [info] crypto: successfully decrypted message.
[13:23:16.477872] [0x00007febd50c7a00] [debug] chunk (1): content-type: multipart/mixed
[13:23:16.477893] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.477915] [0x00007febd50c7a00] [debug] chunk: alternative: false
[13:23:16.477957] [0x00007febd50c7a00] [debug] chunk (2): content-type: multipart/mixed
[13:23:16.477978] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.478002] [0x00007febd50c7a00] [debug] chunk: alternative: false
[13:23:16.478039] [0x00007febd50c7a00] [debug] chunk (3): content-type: text/plain
[13:23:16.478072] [0x00007febd50c7a00] [debug] chunk: preferred.
[13:23:16.478092] [0x00007febd50c7a00] [debug] chunk: is part (viewable: true, attachment: false) 
[13:23:16.478118] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:16.478141] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:16.478164] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:16.478234] [0x00007febd50c7a00] [info] msg: loading mid: 20170220083039.GF10244@vita
[13:23:16.478297] [0x00007febd50c7a00] [info] msg: filename: /home/max/Mails/FSFE/INBOX/cur/1487590654_1.1270.bistromath,U=3393,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
[13:23:16.478474] [0x00007febd50c7a00] [debug] chunk (4): content-type: multipart/encrypted
[13:23:16.478499] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.478565] [0x00007febd50c7a00] [debug] crypto: gpg: gpg2
[13:23:16.486652] [0x00007febd50c7a00] [warning] chunk: is encrypted.
[13:23:16.486715] [0x00007febd50c7a00] [debug] crypto: decrypting and verifiying..
[13:23:16.654724] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [5B19FA89F*******]
[13:23:16.654796] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [20E7C60CC8******]
[13:23:16.654825] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [8B2FE9E6B*******]
[13:23:16.654856] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [0000000000000000]
[13:23:16.654907] [0x00007febd50c7a00] [info] crypto: successfully decrypted message.
[13:23:16.654969] [0x00007febd50c7a00] [debug] chunk (5): content-type: text/plain
[13:23:16.655010] [0x00007febd50c7a00] [debug] chunk: preferred.
[13:23:16.655028] [0x00007febd50c7a00] [debug] chunk: is part (viewable: true, attachment: false) 
[13:23:16.655059] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:16.655122] [0x00007febd50c7a00] [info] msg: loading mid: 9d6768fd-69a4-87ef-e061-7ff2a51c192a@golem.de
[13:23:16.655166] [0x00007febd50c7a00] [info] msg: filename: /home/max/Mails/FSFE/INBOX/cur/1487606872_1.15100.bistromath,U=3403,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
[13:23:16.655365] [0x00007febd50c7a00] [debug] chunk (6): content-type: multipart/encrypted
[13:23:16.655387] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.655460] [0x00007febd50c7a00] [debug] crypto: gpg: gpg2
[13:23:16.663454] [0x00007febd50c7a00] [warning] chunk: is encrypted.
[13:23:16.663525] [0x00007febd50c7a00] [debug] crypto: decrypting and verifiying..
[13:23:16.851326] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [94E4C04********]
[13:23:16.851402] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [20E7C60CC8******]
[13:23:16.851431] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [8B2FE9E6B*******]
[13:23:16.851459] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [5B19FA89F*******]
[13:23:16.851488] [0x00007febd50c7a00] [info] crypto: successfully decrypted message.
[13:23:16.851553] [0x00007febd50c7a00] [debug] chunk (7): content-type: multipart/mixed
[13:23:16.851580] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.851613] [0x00007febd50c7a00] [debug] chunk: alternative: false
[13:23:16.851651] [0x00007febd50c7a00] [debug] chunk (8): content-type: multipart/mixed
[13:23:16.851674] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.851701] [0x00007febd50c7a00] [debug] chunk: alternative: false
[13:23:16.851743] [0x00007febd50c7a00] [debug] chunk (9): content-type: text/plain
[13:23:16.851772] [0x00007febd50c7a00] [debug] chunk: preferred.
[13:23:16.851795] [0x00007febd50c7a00] [debug] chunk: is part (viewable: true, attachment: false) 
[13:23:16.851824] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:16.851848] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:16.851872] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:16.851927] [0x00007febd50c7a00] [info] msg: loading mid: 20170221081043.GI25097@vita
[13:23:16.851971] [0x00007febd50c7a00] [info] msg: filename: /home/max/Mails/FSFE/INBOX/cur/1487673817_1.24858.bistromath,U=3417,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
[13:23:16.852148] [0x00007febd50c7a00] [debug] chunk (10): content-type: multipart/encrypted
[13:23:16.852175] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:16.852242] [0x00007febd50c7a00] [debug] crypto: gpg: gpg2
[13:23:16.862667] [0x00007febd50c7a00] [warning] chunk: is encrypted.
[13:23:16.862766] [0x00007febd50c7a00] [debug] crypto: decrypting and verifiying..
[13:23:17.060534] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [5B19FA89F*******]
[13:23:17.060611] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [20E7C60CC8******]
[13:23:17.060640] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [8B2FE9E6B*******]
[13:23:17.060670] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [0000000000000000]
[13:23:17.060693] [0x00007febd50c7a00] [info] crypto: successfully decrypted message.
[13:23:17.060748] [0x00007febd50c7a00] [debug] chunk (11): content-type: text/plain
[13:23:17.060778] [0x00007febd50c7a00] [debug] chunk: preferred.
[13:23:17.060801] [0x00007febd50c7a00] [debug] chunk: is part (viewable: true, attachment: false) 
[13:23:17.060828] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:17.060881] [0x00007febd50c7a00] [info] msg: loading mid: e6c3da1e-7919-44a4-b91b-ae82520f810a@golem.de
[13:23:17.060924] [0x00007febd50c7a00] [info] msg: filename: /home/max/Mails/FSFE/INBOX/cur/1487678360_0.4054.bistromath,U=3423,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
[13:23:17.061114] [0x00007febd50c7a00] [debug] chunk (12): content-type: multipart/encrypted
[13:23:17.061141] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:17.061209] [0x00007febd50c7a00] [debug] crypto: gpg: gpg2
[13:23:17.069607] [0x00007febd50c7a00] [warning] chunk: is encrypted.
[13:23:17.069674] [0x00007febd50c7a00] [debug] crypto: decrypting and verifiying..
[13:23:17.245531] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [94E4C04********]
[13:23:17.245603] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [20E7C60CC8******]
[13:23:17.245632] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [8B2FE9E6B*******]
[13:23:17.245660] [0x00007febd50c7a00] [debug] cr: encrypted for: () [] [5B19FA89F*******]
[13:23:17.245686] [0x00007febd50c7a00] [info] crypto: successfully decrypted message.
[13:23:17.245738] [0x00007febd50c7a00] [debug] chunk (13): content-type: multipart/mixed
[13:23:17.245764] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:17.245789] [0x00007febd50c7a00] [debug] chunk: alternative: false
[13:23:17.245827] [0x00007febd50c7a00] [debug] chunk (14): content-type: multipart/mixed
[13:23:17.245850] [0x00007febd50c7a00] [debug] chunk: multi part
[13:23:17.245875] [0x00007febd50c7a00] [debug] chunk: alternative: false
[13:23:17.245915] [0x00007febd50c7a00] [debug] chunk (15): content-type: text/plain
[13:23:17.245940] [0x00007febd50c7a00] [debug] chunk: preferred.
[13:23:17.245962] [0x00007febd50c7a00] [debug] chunk: is part (viewable: true, attachment: false) 
[13:23:17.245988] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:17.246018] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:17.246041] [0x00007febd50c7a00] [debug] chunk: multi part end
[13:23:17.246154] [0x00007febd50c7a00] [info] render: loading html..
[13:23:17.246553] [0x00007febd50c7a00] [info] tv: navigation action: 5
[13:23:17.246583] [0x00007febd50c7a00] [info] tv: navigating to: /home/max/.config/astroid/rnbot5tm51pth4hekv1bbnqn0l2c2idfvexg78g33ufgsgzbjozyyprpgeufw1iwwxpz6jizzb5ssliffnjase71gp62z3we4xtoanklb9n1vcedwad4u8r4
[13:23:17.246658] [0x00007febd50c7a00] [debug] tv: on_load_changed: 0
[13:23:17.246808] [0x00007febd50c7a00] [info] db: closing db.
[13:23:17.246878] [0x00007febd50c7a00] [debug] db: ro: waiting for lock to close..
[13:23:17.246900] [0x00007febd50c7a00] [debug] db: ro: closing..
[13:23:17.255776] [0x00007febd50c7a00] [debug] tv: on_load_changed: 1
[13:23:17.267311] [0x00007febd50c7a00] [debug] tv: on_load_changed: 3
[13:23:17.267464] [0x00007febd50c7a00] [debug] tv: on_load_changed: 2
[13:23:17.267493] [0x00007febd50c7a00] [debug] tv: load finished.
[13:23:17.269549] [0x00007febd50c7a00] [debug] render: html loaded, building messages..
[13:23:17.269603] [0x00007febd50c7a00] [debug] tv: adding message: 4d4ea9bc-d967-3e3b-d968-74c533af61e3@golem.de
[13:23:17.271636] [0x00007febd50c7a00] [debug] create message part: 0 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/encrypted)
[13:23:17.271709] [0x00007febd50c7a00] [debug] create message part: 1 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/mixed)
[13:23:17.271739] [0x00007febd50c7a00] [debug] create message part: 2 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/mixed)
[13:23:17.271768] [0x00007febd50c7a00] [debug] create message part: 3 (siblings: 0) (kids: 0) (attachment: false) (viewable: true) (mimetype: text/plain)
[13:23:17.271794] [0x00007febd50c7a00] [debug] create body part: 3
[13:23:17.271877] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.271912] [0x00007febd50c7a00] [debug] chunk: plain text (out html: true)
[13:23:17.271957] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.272006] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.272717] [0x00007febd50c7a00] [debug] tv: added encrypt: 3

(astroid:32435): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[13:23:17.273044] [0x00007febd50c7a00] [debug] tv: make preview..
[13:23:17.273092] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.273121] [0x00007febd50c7a00] [debug] chunk: plain text (out html: false)
[13:23:17.273152] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.273182] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.295996] [0x00007febd50c7a00] [debug] tv: adding message: 20170220083039.GF10244@vita
[13:23:17.296771] [0x00007febd50c7a00] [debug] create message part: 4 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/encrypted)
[13:23:17.296813] [0x00007febd50c7a00] [debug] create message part: 5 (siblings: 0) (kids: 0) (attachment: false) (viewable: true) (mimetype: text/plain)
[13:23:17.296844] [0x00007febd50c7a00] [debug] create body part: 5
[13:23:17.296902] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.296929] [0x00007febd50c7a00] [debug] chunk: plain text (out html: true)
[13:23:17.296962] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.296992] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.297267] [0x00007febd50c7a00] [debug] tv: added encrypt: 5
[13:23:17.297389] [0x00007febd50c7a00] [debug] tv: make preview..
[13:23:17.297421] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.297445] [0x00007febd50c7a00] [debug] chunk: plain text (out html: false)
[13:23:17.297474] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.297500] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.297974] [0x00007febd50c7a00] [debug] tv: adding message: 9d6768fd-69a4-87ef-e061-7ff2a51c192a@golem.de
[13:23:17.298580] [0x00007febd50c7a00] [debug] create message part: 6 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/encrypted)
[13:23:17.298620] [0x00007febd50c7a00] [debug] create message part: 7 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/mixed)
[13:23:17.298655] [0x00007febd50c7a00] [debug] create message part: 8 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/mixed)
[13:23:17.298689] [0x00007febd50c7a00] [debug] create message part: 9 (siblings: 0) (kids: 0) (attachment: false) (viewable: true) (mimetype: text/plain)
[13:23:17.298720] [0x00007febd50c7a00] [debug] create body part: 9
[13:23:17.298783] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.298806] [0x00007febd50c7a00] [debug] chunk: plain text (out html: true)
[13:23:17.298835] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.298853] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.299237] [0x00007febd50c7a00] [debug] tv: added encrypt: 9

(astroid:32435): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[13:23:17.299418] [0x00007febd50c7a00] [debug] tv: make preview..
[13:23:17.299448] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.299465] [0x00007febd50c7a00] [debug] chunk: plain text (out html: false)
[13:23:17.299487] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.299505] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.299986] [0x00007febd50c7a00] [debug] tv: adding message: 20170221081043.GI25097@vita
[13:23:17.300608] [0x00007febd50c7a00] [debug] create message part: 10 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/encrypted)
[13:23:17.300645] [0x00007febd50c7a00] [debug] create message part: 11 (siblings: 0) (kids: 0) (attachment: false) (viewable: true) (mimetype: text/plain)
[13:23:17.300665] [0x00007febd50c7a00] [debug] create body part: 11
[13:23:17.300712] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.300734] [0x00007febd50c7a00] [debug] chunk: plain text (out html: true)
[13:23:17.300754] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.300772] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.301078] [0x00007febd50c7a00] [debug] tv: added encrypt: 11
[13:23:17.301187] [0x00007febd50c7a00] [debug] tv: make preview..
[13:23:17.301214] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.301231] [0x00007febd50c7a00] [debug] chunk: plain text (out html: false)
[13:23:17.301251] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.301270] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.301740] [0x00007febd50c7a00] [debug] tv: adding message: e6c3da1e-7919-44a4-b91b-ae82520f810a@golem.de
[13:23:17.302327] [0x00007febd50c7a00] [debug] create message part: 12 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/encrypted)
[13:23:17.302364] [0x00007febd50c7a00] [debug] create message part: 13 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/mixed)
[13:23:17.302390] [0x00007febd50c7a00] [debug] create message part: 14 (siblings: 0) (kids: 1) (attachment: false) (viewable: false) (mimetype: multipart/mixed)
[13:23:17.302415] [0x00007febd50c7a00] [debug] create message part: 15 (siblings: 0) (kids: 0) (attachment: false) (viewable: true) (mimetype: text/plain)
[13:23:17.302439] [0x00007febd50c7a00] [debug] create body part: 15
[13:23:17.302492] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.302518] [0x00007febd50c7a00] [debug] chunk: plain text (out html: true)
[13:23:17.302549] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.302576] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.302990] [0x00007febd50c7a00] [debug] tv: added encrypt: 15

(astroid:32435): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[13:23:17.303173] [0x00007febd50c7a00] [debug] tv: make preview..
[13:23:17.303202] [0x00007febd50c7a00] [debug] chunk: body: part
[13:23:17.303228] [0x00007febd50c7a00] [debug] chunk: plain text (out html: false)
[13:23:17.303255] [0x00007febd50c7a00] [debug] enc: quoted-printable
[13:23:17.303281] [0x00007febd50c7a00] [debug] charset: utf-8
[13:23:17.303848] [0x00007febd50c7a00] [debug] tv: no message expanded, showing newest message.
[13:23:17.303916] [0x00007febd50c7a00] [debug] tv: focusing: Tue, 21 Feb 2017 12:56:43 +0100
[13:23:17.325823] [0x00007febd50c7a00] [info] tv: ready emitted.
[13:23:17.328857] [0x00007febd50c7a00] [debug] tv: re-doing scroll.
[13:23:24.322290] [0x00007febd50c7a00] [debug] extension: destruct.
[13:23:24.322895] [0x00007febd50c7a00] [debug] tv: deconstruct.
[13:23:24.329322] [0x00007febd50c7a00] [debug] chunk: deconstruct.
[13:23:24.329538] [0x00007febd50c7a00] [debug] chunk: deconstruct.
[13:23:24.329601] [0x00007febd50c7a00] [debug] chunk: deconstruct.
[13:23:24.329650] [0x00007febd50c7a00] [debug] chunk: deconstruct.
[13:23:24.329698] [0x00007febd50c7a00] [debug] crypto: deconstruct.

(astroid:32435): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
fish: 'astroid --no-auto-poll' terminated by signal SIGSEGV (Adressbereichsfehler)
```

**Comment by gauteh** [comment]
M. Dietrich writes on januar 31, 2017 20:09:
> the feature still exists :(
> 
> it now mainly gets stuck when starting the embedded editor (happened 3 times for me now).

I assume this is only when you have encryption or signing on by default?
Which one in that case?

**Comment by gauteh** [comment]
Max writes on februar 21, 2017 13:30:
> With the crypto branch, I experience strange, reproducable crashes:
> 
> 1. Open a thread, containing encrypted (or only encrypted?) mails
> 2. Close the thread by pressing "x" in my case

Hi, can you try again with latest changes.

**Comment by mxmehl** [comment]
Am 21.02.2017 um 14:16 schrieb Gaute Hope:
> Max writes on februar 21, 2017 13:30:
>> With the crypto branch, I experience strange, reproducable crashes:
>>
>> 1. Open a thread, containing encrypted (or only encrypted?) mails
>> 2. Close the thread by pressing "x" in my case
> 
> Hi, can you try again with latest changes.

Cool thx, I cannot reproduce the crash anymore so it seems to work.
Keeping an eye on it anyway.

Best,
Max

**Comment by gauteh** [comment]
hopefully fixed in #286.
