### ISSUE TITLE
astroid crashes every time I try to open it, on either of two machines

### ISSUE THREAD

**Issue by mwotton** [astroidmail/astroid#348]
```
[20:08:05.389651] [0x00007f3242ffd700] [error] address: more than one address in list!
[20:08:05.398569] [0x00007f326b641ac0] [debug] ql: loaded 1700 threads.
[20:08:05.425663] [0x00007f326b641ac0] [debug] ql: loaded 1800 threads.
[20:08:05.453471] [0x00007f326b641ac0] [debug] ql: loaded 1900 threads.
[20:08:05.481154] [0x00007f326b641ac0] [debug] ql: loaded 2000 threads.
[20:08:05.508855] [0x00007f326b641ac0] [debug] ql: loaded 2100 threads.
[20:08:05.536381] [0x00007f326b641ac0] [debug] ql: loaded 2200 threads.
[20:08:05.564022] [0x00007f326b641ac0] [debug] ql: loaded 2300 threads.
[20:08:05.602776] [0x00007f326b641ac0] [debug] ql: loaded 2400 threads.
[20:08:05.637151] [0x00007f326b641ac0] [debug] ql: loaded 2500 threads.
[20:08:05.668272] [0x00007f326b641ac0] [debug] ql: loaded 2600 threads.
[20:08:05.732080] [0x00007f326b641ac0] [debug] ql: loaded 2700 threads.
[20:08:05.766141] [0x00007f326b641ac0] [debug] ql: loaded 2800 threads.
[20:08:05.793461] [0x00007f326b641ac0] [debug] ql: loaded 2900 threads.
[20:08:05.821719] [0x00007f326b641ac0] [debug] ql: loaded 3000 threads.
[20:08:05.851052] [0x00007f326b641ac0] [debug] ql: loaded 3100 threads.
[20:08:05.881123] [0x00007f326b641ac0] [debug] ql: loaded 3200 threads.
[20:08:05.910201] [0x00007f326b641ac0] [debug] ql: loaded 3300 threads.
[20:08:05.936679] [0x00007f326b641ac0] [debug] ql: loaded 3400 threads.
[20:08:05.961790] [0x00007f326b641ac0] [debug] ql: loaded 3500 threads.
[20:08:05.989574] [0x00007f326b641ac0] [debug] ql: loaded 3600 threads.
[20:08:06.024657] [0x00007f326b641ac0] [debug] ql: loaded 3700 threads.
[20:08:06.057941] [0x00007f326b641ac0] [debug] ql: loaded 3800 threads.
[20:08:06.097136] [0x00007f326b641ac0] [debug] ql: loaded 3900 threads.
[20:08:06.137273] [0x00007f326b641ac0] [debug] ql: loaded 4000 threads.
[20:08:06.168789] [0x00007f326b641ac0] [debug] ql: loaded 4100 threads.
[20:08:06.206308] [0x00007f326b641ac0] [debug] ql: loaded 4200 threads.
[20:08:06.240236] [0x00007f326b641ac0] [debug] ql: loaded 4300 threads.
[20:08:06.273227] [0x00007f326b641ac0] [debug] ql: loaded 4400 threads.
[20:08:06.303149] [0x00007f326b641ac0] [debug] ql: loaded 4500 threads.
[20:08:06.333587] [0x00007f326b641ac0] [debug] ql: loaded 4600 threads.
[20:08:06.364702] [0x00007f326b641ac0] [debug] ql: loaded 4700 threads.
[20:08:06.399386] [0x00007f326b641ac0] [debug] ql: loaded 4800 threads.
[20:08:06.435048] [0x00007f326b641ac0] [debug] ql: loaded 4900 threads.
[20:08:06.465734] [0x00007f326b641ac0] [debug] ql: loaded 5000 threads.
[20:08:06.493637] [0x00007f326b641ac0] [debug] ql: loaded 5100 threads.
[20:08:06.518370] [0x00007f326b641ac0] [debug] ql: loaded 5200 threads.
[20:08:06.546645] [0x00007f326b641ac0] [debug] ql: loaded 5300 threads.
[20:08:06.574840] [0x00007f326b641ac0] [debug] ql: loaded 5400 threads.
[20:08:06.600078] [0x00007f326b641ac0] [debug] ql: loaded 5500 threads.
[20:08:06.626288] [0x00007f326b641ac0] [debug] ql: loaded 5600 threads.
[20:08:06.657438] [0x00007f326b641ac0] [debug] ql: loaded 5700 threads.
[20:08:06.680708] [0x00007f326b641ac0] [debug] ql: loaded 5800 threads.
[20:08:06.707609] [0x00007f326b641ac0] [debug] ql: loaded 5900 threads.
[20:08:06.735658] [0x00007f326b641ac0] [debug] ql: loaded 6000 threads.
[20:08:06.760193] [0x00007f326b641ac0] [debug] ql: loaded 6100 threads.
[20:08:06.787998] [0x00007f326b641ac0] [debug] ql: loaded 6200 threads.
[20:08:06.836368] [0x00007f326b641ac0] [debug] ql: loaded 6300 threads.
[20:08:06.864373] [0x00007f326b641ac0] [debug] ql: loaded 6400 threads.
[20:08:06.894373] [0x00007f326b641ac0] [debug] ql: loaded 6500 threads.
[20:08:06.920750] [0x00007f326b641ac0] [debug] ql: loaded 6600 threads.
[20:08:06.947554] [0x00007f326b641ac0] [debug] ql: loaded 6700 threads.
[20:08:06.972317] [0x00007f326b641ac0] [debug] ql: loaded 6800 threads.
[20:08:06.997370] [0x00007f326b641ac0] [debug] ql: loaded 6900 threads.
[20:08:07.022617] [0x00007f326b641ac0] [debug] ql: loaded 7000 threads.
[20:08:07.051717] [0x00007f326b641ac0] [debug] ql: loaded 7100 threads.
[20:08:07.079250] [0x00007f326b641ac0] [debug] ql: loaded 7200 threads.
[20:08:07.106285] [0x00007f326b641ac0] [debug] ql: loaded 7300 threads.
[20:08:07.135430] [0x00007f326b641ac0] [debug] ql: loaded 7400 threads.
[20:08:07.164759] [0x00007f326b641ac0] [debug] ql: loaded 7500 threads.
[20:08:07.193607] [0x00007f326b641ac0] [debug] ql: loaded 7600 threads.
[20:08:07.222323] [0x00007f326b641ac0] [debug] ql: loaded 7700 threads.
[20:08:07.251330] [0x00007f326b641ac0] [debug] ql: loaded 7800 threads.
[20:08:07.277724] [0x00007f326b641ac0] [debug] ql: loaded 7900 threads.
[20:08:07.303776] [0x00007f326b641ac0] [debug] ql: loaded 8000 threads.
[20:08:07.328474] [0x00007f326b641ac0] [debug] ql: loaded 8100 threads.
[20:08:07.356864] [0x00007f326b641ac0] [debug] ql: loaded 8200 threads.
[20:08:07.384243] [0x00007f326b641ac0] [debug] ql: loaded 8300 threads.
[20:08:07.414525] [0x00007f326b641ac0] [debug] ql: loaded 8400 threads.
[20:08:07.443261] [0x00007f326b641ac0] [debug] ql: loaded 8500 threads.
[20:08:07.468056] [0x00007f326b641ac0] [debug] ql: loaded 8600 threads.
[20:08:07.494501] [0x00007f326b641ac0] [debug] ql: loaded 8700 threads.
[20:08:07.521393] [0x00007f326b641ac0] [debug] ql: loaded 8800 threads.
[20:08:07.550528] [0x00007f326b641ac0] [debug] ql: loaded 8900 threads.
[20:08:07.579601] [0x00007f326b641ac0] [debug] ql: loaded 9000 threads.
[20:08:07.608343] [0x00007f326b641ac0] [debug] ql: loaded 9100 threads.
[20:08:07.639022] [0x00007f326b641ac0] [debug] ql: loaded 9200 threads.
[20:08:07.667453] [0x00007f326b641ac0] [debug] ql: loaded 9300 threads.
[20:08:07.695151] [0x00007f326b641ac0] [debug] ql: loaded 9400 threads.
[20:08:07.724591] [0x00007f326b641ac0] [debug] ql: loaded 9500 threads.
[20:08:07.755143] [0x00007f326b641ac0] [debug] ql: loaded 9600 threads.
[20:08:07.783787] [0x00007f326b641ac0] [debug] ql: loaded 9700 threads.
[20:08:07.814398] [0x00007f326b641ac0] [debug] ql: loaded 9800 threads.
[20:08:07.839971] [0x00007f326b641ac0] [debug] ql: loaded 9900 threads.
[20:08:07.864967] [0x00007f326b641ac0] [debug] ql: loaded 10000 threads.
[20:08:07.902624] [0x00007f326b641ac0] [debug] ql: loaded 10100 threads.
[20:08:08.052459] [0x00007f326b641ac0] [debug] ql: loaded 10200 threads.
[20:08:08.098803] [0x00007f326b641ac0] [debug] ql: loaded 10300 threads.
[20:08:08.157144] [0x00007f326b641ac0] [debug] ql: loaded 10400 threads.
[20:08:08.180860] [0x00007f326b641ac0] [debug] ql: loaded 10500 threads.
[20:08:08.206623] [0x00007f326b641ac0] [debug] ql: loaded 10600 threads.
[20:08:08.235471] [0x00007f326b641ac0] [debug] ql: loaded 10700 threads.
[20:08:08.262951] [0x00007f326b641ac0] [debug] ql: loaded 10800 threads.
[20:08:08.291958] [0x00007f326b641ac0] [debug] ql: loaded 10900 threads.
[20:08:08.319865] [0x00007f326b641ac0] [debug] ql: loaded 11000 threads.
[20:08:08.345407] [0x00007f326b641ac0] [debug] ql: loaded 11100 threads.
[20:08:08.371463] [0x00007f326b641ac0] [debug] ql: loaded 11200 threads.
[20:08:08.399962] [0x00007f326b641ac0] [debug] ql: loaded 11300 threads.
[20:08:08.425871] [0x00007f326b641ac0] [debug] ql: loaded 11400 threads.
[20:08:08.454109] [0x00007f326b641ac0] [debug] ql: loaded 11500 threads.
[20:08:08.478760] [0x00007f326b641ac0] [debug] ql: loaded 11600 threads.
[20:08:08.504853] [0x00007f326b641ac0] [debug] ql: loaded 11700 threads.
[20:08:08.531974] [0x00007f326b641ac0] [debug] ql: loaded 11800 threads.
[20:08:08.560199] [0x00007f326b641ac0] [debug] ql: loaded 11900 threads.
[20:08:08.587976] [0x00007f326b641ac0] [debug] ql: loaded 12000 threads.
[20:08:08.616797] [0x00007f326b641ac0] [debug] ql: loaded 12100 threads.
[20:08:08.646664] [0x00007f326b641ac0] [debug] ql: loaded 12200 threads.
[20:08:08.675016] [0x00007f326b641ac0] [debug] ql: loaded 12300 threads.
[20:08:08.704294] [0x00007f326b641ac0] [debug] ql: loaded 12400 threads.
[20:08:08.736365] [0x00007f326b641ac0] [debug] ql: loaded 12500 threads.
[20:08:09.411855] [0x00007f326b641ac0] [debug] ql: loaded 12600 threads.
[20:08:09.455179] [0x00007f326b641ac0] [debug] ql: loaded 12700 threads.
[20:08:09.521228] [0x00007f326b641ac0] [debug] ql: loaded 12800 threads.
[20:08:09.559745] [0x00007f326b641ac0] [debug] ql: loaded 12900 threads.
[20:08:09.587034] [0x00007f326b641ac0] [debug] ql: loaded 13000 threads.
[20:08:09.795928] [0x00007f326b641ac0] [debug] ql: loaded 13100 threads.
[20:08:09.820770] [0x00007f326b641ac0] [debug] ql: loaded 13200 threads.
[20:08:09.855811] [0x00007f326b641ac0] [debug] ql: loaded 13300 threads.
[20:08:10.156982] [0x00007f326b641ac0] [debug] ql: loaded 13400 threads.
[20:08:10.238151] [0x00007f326b641ac0] [debug] ql: loaded 13500 threads.
[20:08:10.265660] [0x00007f326b641ac0] [debug] ql: loaded 13600 threads.
[20:08:10.328076] [0x00007f326b641ac0] [debug] ql: loaded 13700 threads.
[20:08:10.353182] [0x00007f326b641ac0] [debug] ql: loaded 13800 threads.
[20:08:10.393938] [0x00007f326b641ac0] [debug] ql: loaded 13900 threads.
[20:08:10.406694] [0x00007f3242ffd700] [info] db: closing db.
[20:08:10.406756] [0x00007f3242ffd700] [debug] db: ro: waiting for lock to close..
[20:08:10.406770] [0x00007f3242ffd700] [debug] db: ro: closing..
terminate called after throwing an instance of 'Xapian::DatabaseModifiedError'
[1]    19115 abort      ./astroid
orb ➜  ~/src/astroid git:(master) 
```

**Comment by gauteh** [comment]
Mark Wotton writes on mai 23, 2017 2:09:
> ```
> [20:08:10.406770] [0x00007f3242ffd700] [debug] db: ro: closing..
> terminate called after throwing an instance of 'Xapian::DatabaseModifiedError'
> [1]    19115 abort      ./astroid
> orb ➜  ~/src/astroid git:(master) 
> ```

This can happen if the notmuch db has been modified externally. Do you
have `notmuch new` or the poll script runnning? You can try to start
astroid with: `$ astroid --no-auto-poll`. 

It looks like you have a quite big startup query, this shouldn't really
be a problem, but it is probably the combination of it and some
modification thing to the db that is running. Have you done anything to
the threads? Like archive or change tags?

What version of notmuch / xapian are you using?

**Comment by gauteh** [comment]
Need more info on this one, will close if not.

**Comment by mwotton** [comment]
Sorry, been traveling. Muchsync was running at the time, yes. I'll try with
that flag soon.

**Comment by gauteh** [comment]
Mark Wotton writes on mai 25, 2017 14:09:
> Sorry, been traveling. Muchsync was running at the time, yes. I'll try with
> that flag soon.

Ok, this is an issue I keep running into with notmuch. If the db is
changed too much during long running queries these things happen. I
think it was solved earlier by running notmuch new or muchsync in the
poll script so that the db is read-write locked inside astroid at the
time. That might work for you.

**Comment by gauteh** [comment]
Do you have more info on this? Otherwise I will be closing this issue.

**Comment by mwotton** [comment]
gah, forgot about this completely. sorry about that and thanks for your patience, i'll try it now.

**Comment by mwotton** [comment]
So, yeah, still crashing. Reading the docs again suggests that I should be notifying astroid whenever the db is refreshed, but perhaps it might be worth catching the DatabaseModifiedError and letting the user know they've screwed up the setup by some means more gentle than aborting the program?

**Comment by gauteh** [comment]
Mark Wotton writes on juni 8, 2017 15:20:
> So, yeah, still crashing. Reading the docs again suggests that I should be notifying astroid whenever the db is refreshed, but perhaps it might be worth catching the DatabaseModifiedError and letting the user know they've screwed up the setup by some means more gentle than aborting the program?
> 

It can't be caught, it is on the other side of the notmuch C-API. So,
only way to catch it is by catching the SIGSEGV from notmuch which I
think is too much hassle.

**Comment by mwotton** [comment]
Righto.

**Comment by gauteh** [comment]
Mark Wotton writes on juni 8, 2017 15:23:
> Righto.

Alright, it can probably be solved by running the sync operation through
the poll script or something similar to that. Otherwise, I think it is a
notmuch bug since there currently isn't a way for me to handle the
error.
