### ISSUE TITLE
GTK can't close astroid with the little X

### ISSUE THREAD

**Issue by hugoroy** [astroidmail/astroid#377]
Nothing happens when the pointer goes over the X or if I click on it.

![capture d ecran de 2017-08-05 14-19-49](https://user-images.githubusercontent.com/1629771/28995432-4bf39b38-79e9-11e7-954a-2c3f052fed36.png)

**Comment by gauteh** [comment]
Does it say anything in the log? Do you have any drafts open? I can close here (using openbox, should be the same).

**Comment by hugoroy** [comment]
On 2017-08-10 11:29, Gaute Hope wrote:
> Does it say anything in the log? Do you have any drafts open? I can
> close here (using openbox, should be the same).

No, i don't see anything in the log at all (I tried that already).

I will check again if this was caused by a draft (but I don't think it 
was, IIRC I tried opening again from scratch and it didn't work).

Maybe related to some recent GTK updates.

I will test again tonight :-)

Hugo

**Comment by hugoroy** [comment]
↪ Hugo Roy / août 10, 2017 11:32:
> I will check again if this was caused by a draft (but I don't think it 
> was, IIRC I tried opening again from scratch and it didn't work).

No, nothing special.

**Comment by gauteh** [comment]
Weird, could be related to the grab_modal stuff. We rely on that pretty 
heavily though for the keybindings to work as they should.

**Comment by gauteh** [comment]
Is this still an issue?

**Comment by hugoroy** [comment]
↪ Gaute Hope / octobre 26, 2017 11:59:
> Is this still an issue?
> 


Yes. But it's not a big issue honestly.

At this point, I should probably give you more info. What do you need? :)

**Comment by gauteh** [comment]
Hugo Roy writes on oktober 27, 2017 22:55:
> ↪ Gaute Hope / octobre 26, 2017 11:59:
>> Is this still an issue?
>> 
> 
> Yes. But it's not a big issue honestly.
> 
> At this point, I should probably give you more info. What do you need? :)

I don't know! Do you know if anyone else has the same problem?

**Comment by francesquini** [comment]
Same here on Ubuntu 17.10.

**Comment by gauteh** [comment]
Is anything shown in the debug log when you click the X?

**Comment by hugoroy** [comment]
↪ Gaute Hope / décembre 25, 2017 19:39:
> Is anything shown in the debug log when you click the X?

Nothing happens for me.

**Comment by gauteh** [comment]
Can you check if this is fixed after #558 was merged?

**Comment by gauteh** [comment]
I think this is fixed.

**Comment by hugoroy** [comment]
↪ Gaute Hope / 2018-11-21, 20:13 (CET):
> I think this is fixed.
> 

This is not fixed in version 0.14 unfortunately.

**Comment by gauteh** [comment]
Hooray!

**Comment by hugoroy** [comment]
I'm a bit sad that it's magically fixed without being able to provide more info :-))

But yeah: hourray!!

Thanks for your patience!

Le 17 janvier 2019 19:48:58 GMT+01:00, Gaute Hope <notifications@github.com> a écrit :
>Hooray!

-- 
Envoyé de mon appareil mobile
Sent from my mobile device

**Comment by hugoroy** [comment]
Oh my god...

The problem is back.

I have no more clue.


↪ Gaute Hope / 2019-01-17, 22:24 (CET):
> Hehe yeah, though I had no clue as to what was wrong
> 
> tor. 17. jan. 2019 kl. 22:04 skrev Hugo Roy <notifications@github.com>:
> 
>> I'm a bit sad that it's magically fixed without being able to provide more
>> info :-))
>>
>> But yeah: hourray!!
>>
>> Thanks for your patience!
>>
>> Le 17 janvier 2019 19:48:58 GMT+01:00, Gaute Hope <

**Comment by hugoroy** [comment]
I didn't do anything specific (well, I did update some software on my system, - the usual). So I'm really clueless and as usual there's nothing in the logs that I can point to - it's really as if the windows' "x" and the "yes"/"no" dialogs when pressing "q" for quitting did not detect the pointer at all.

↪ Hugo Roy / 2019-01-19, 19:01 (CET):
> Oh my god...
> 
> The problem is back.
> 
> I have no more clue.
> 
> 
> ↪ Gaute Hope / 2019-01-17, 22:24 (CET):
>> Hehe yeah, though I had no clue as to what was wrong
>> 
>> tor. 17. jan. 2019 kl. 22:04 skrev Hugo Roy <notifications@github.com>:
>> 
>>> I'm a bit sad that it's magically fixed without being able to provide more
>>> info :-))
>>>
>>> But yeah: hourray!!
>>>
>>> Thanks for your patience!
>>>
>>> Le 17 janvier 2019 19:48:58 GMT+01:00, Gaute Hope <
