### ISSUE TITLE
Remove "format=flowed"

### ISSUE THREAD

**Issue by mxmehl** [astroidmail/astroid#446]
Astroid sends email with the header `Content-Type: text/plain; charset=utf-8; format=flowed`. The last part seems to create some embarrassing line breaks, especially when writing longer lines than 76 encoded characters (or umlauts which stretch the editor's wrap width after encoding).

Anyway, `format=flowed` [seems to be a rather broken standard](https://blog.fastmail.com/2016/12/17/format-flowed/), and most mail clients don't use it (any more). Is there any reason astroid uses it? And would it cause issues when removing it?

**Comment by mrvdb** [comment]
Please keep it as an option

**Comment by kirschner** [comment]
I also had quite embarrassing problems with that, as the e-mail looked absolutely unprofessional because of that bug. Thanks @mxmehl for researching and reporting!

**Comment by mxmehl** [comment]
Perhaps as additional info: The bug only seems to occur on mail clients which support format=flowed. In my and @kirschner's case this was on Claws Mails IMHO.

**Comment by kirschner** [comment]
First time I got that feedback was from an Evolution user, though.

**Comment by mrvdb** [comment]
@mxmehl Are there more details on the bug other than "embarassing line breaks" ? I've been a long time claws user and migrated to astroid from it.

**Comment by mxmehl** [comment]
I don't have a screenshot to share but I'll try to explain.

In vim I have a fixed line width of 72. In quoted-printable, the maximum width is 76 characters. For example, if you use special characters like umlauts which are escaped by quoted-printable you exceed the 76 character limit. A raw text therefore could look like this (3 lines):

```
Bj=C3=B6rn, k=C3=B6nntest Du mir bitte die besagte Mail komplett forwarden?=
 Dann
gucke ich mal, ob man da was herausfinden kann.
```
In my original text, `Dann` was on the first line, and after it came a normal line break. The `=` at the end of the first line indicates a soft line break which shouldn't be visible after decoding quoted printable. So in the end, it should be 2 lines.

On a client which respects format=flowed, this looks like:

```
Björn, könntest Du mir bitte die besagte Mail komplett forwarden?
 Dann
gucke ich mal, ob man da was herausfinden kann.
```

So format=flowed seems to interpret the soft line break as a hard line break. 

And since the `=` is also used as escape character, the wrong interpretation also causes umlauts to break. This happens if an escaped umlaut (e.g. `=C3=BC` for `ü`) is cut in between by a soft line break:

```
W=C3=BCrde mich freuen, wenn wir dieses Jahr xxxxxxxxx als yyyyyyy begr=C3=
=BC=C3=9Fen
d=C3=BCrfen.=20
```

I'm not quite sure how the `=` character is handled with format=flowed and quoted-printable but at least in Claws it breaks lots of things.

**Comment by jlombera** [comment]
This is not a bug.  Please take a look at https://www.ietf.org/rfc/rfc2646.txt to understand how to f=f works and how compliant clients are supposed to format these emails.  In any case, please leave this as an option, since is a very useful feature for plain text emails (hard line breaks are a nuance in deep quoted messages in a thread).

**Comment by gauteh** [comment]
FYI, in VIM you can use: `{gq}` to re-wrap a quoted paragraph. It can be added as an option, PR's welcome - shouldn't be too hard.

**Comment by gauteh** [comment]
According to the standard (ref https://github.com/astroidmail/astroid/issues/446#issuecomment-353787747) the editor should wrap lines according to some rules. In VIM this can be probably be achieved with `textwidth` and friends. If anyone has any good defaults for this (not already included with the standard `ft=mail`?) please share!

**Comment by gauteh** [comment]
Fixed in #463. Now configurable.

**Comment by gauteh** [comment]
https://github.com/astroidmail/astroid/wiki/Configuration-Reference#mailformat_flowed

**Comment by mxmehl** [comment]
Wow, thanks for merging and making configurable. Now I understand how to add config options for the next time.

One thing I'd like to change: Can't we make mail.format_flowed false by default? I use a pretty standard vim config and it doesn't seem to work well with format_flowed. Is there any standard editor compatible with it when a text width is defined (which is still recommended for text mails in many setups)?

**Comment by gauteh** [comment]
Max writes on februar 6, 2018 15:24:
> One thing I'd like to change: Can't we make mail.format_flowed false 
> by default? I use a pretty standard vim config and it doesn't seem to 
> work well with format_flowed. Is there any standard editor compatible 
> with it when a text width is defined (which is still recommended for 
> text mails in many setups)?

I'm not necessarily opposed.

I think this works for vim:

```
  " format=flowed
  au FileType mail setlocal tw=72
  au FileType mail setlocal fo+=q
  au FileType mail setlocal comments+=nb:>
```

https://vi.stackexchange.com/questions/6773/how-can-i-make-vims-flowing-aware-of-email-replies

Perhaps we should add this to the suggested options for vim.

I also use:

```
" Rewrap paragraph
map <silent> <S-q> {gq}<Bar>:echo "Rewrapped paragraph"<CR>
``` 

to re-wrap existing paragraphs - this respects the quoting char.

**Comment by mxmehl** [comment]
> I think this works for vim:

Thanks but I think it doesn't solve the underlying problem: Astroid doesn't do any space stuffing which makes lines shorter than 79 characters, and it uses quoted-printable with format=flowed which is not recommended in [RFC 2646](https://www.ietf.org/rfc/rfc2646) (~ Page 5).

So I withdraw what I said before: I don't think an editor has to support format=flowed, it's about the client.

**Comment by gauteh** [comment]
Max writes on februar 6, 2018 15:50:
>> I think this works for vim:
> 
> Thanks but I think it doesn't solve the underlying problem: Astroid 
> doesn't do any space stuffing which makes lines shorter than 79 
> characters, and it uses quoted-printable with format=flowed which is 
> not recommended in [RFC 2646](https://www.ietf.org/rfc/rfc2646) (~ 
> Page 5).
> 
> So I withdraw what I said before: I don't think an editor has to 
> support format=flowed, it's about the client.
> 

Right, not a big deal for me what the default is. Anyone else with thoughts on 
format=flowed default off?

**Comment by gauteh** [comment]
Now off by default.
